# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
    win: circleci/windows@4.1

# Define the jobs we want to run for this project
jobs:
  build:
    executor:
        name: win/default
        size: "medium"
    steps:
      - checkout
      - run: 
          name: Run Build Step
          command: dotnet build -c Release
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    executor:
        name: win/default
        size: "medium"
    steps:
      - attach_workspace:
          at: .
      - run: dotnet test -c Release
      - run:
          name: Run Tests
          when: always
          command: |
              dotnet tool install -g trx2junit
              trx2junit TestResults\*.trx
      - store_test_results:
          path: TestResults
      - store_artifacts:
          path: HQDotNet-Core\bin\Release\netstandard2.1\HQDotNet.Core.dll
          destination: artifacts\Release\netstandard2.1\HQDotNet.Core.dll
      - store_artifacts:
          path: HQDotNet-Core\bin\Release\netstandard2.1\HQDotNet.Model.dll
          destination: artifacts\Release\netstandard2.1\HQDotNet.Model.dll
          
      - persist_to_workspace:
          root: .
          paths:
            - .
              # PATH="${PATH}:/root/.dotnet/tools"

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete "v0.1.1" ./artifacts/

workflows:
  HQDotNet.Core-Release:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish-github-release:
          requires:
            - test