# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
    win: circleci/windows@4.1

# Define the jobs we want to run for this project
jobs:
  build:
    executor:
        name: win/default
        size: "medium"
    steps:
      - checkout
      - run: 
          name: "Run Build Step"
          command: dotnet.exe build
  test:
    executor:
        name: win/default
        size: "medium"
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  HQDotNet.Core-build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
