# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet:latest
        auth:
          username: stonemonkeystudios
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var 
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: mcr.microsoft.com/dotnet:latest
        auth:
          username: stonemonkeystudios
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var 
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  HQDotNet.Core-build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
